#ifndef EDITDIALOG_H
#define EDITDIALOG_H

#include <QDialog> // Class for creating dialog windows (pop-up windows that are secondary to the main window). Used for the Edit window

namespace Ui {
class EditDialog;
}

class EditDialog : public QDialog
{
    Q_OBJECT

public:
    explicit EditDialog(QWidget *parent = nullptr);
    ~EditDialog();

    // Added member function declarations
    // The & operator is used to get the address of a variable, which is what we store in a pointer.
    void setValues(const QString &brand, const QString &color, const QString &itemNumber, const QString &type, const QString &collection, const QString &quantity, const QString &imagePath);
    QString getBrand() const;
    QString getColor() const;
    QString getItemNumber() const;
    QString getType() const;
    QString getCollection() const;
    QString getQuantity() const;
    QString getImagePath() const;

private slots:
    void on_buttonUploadImage_clicked();

    void on_buttonDeleteImage_clicked();

private:
    Ui::EditDialog *ui;
    // To store the path of the uploaded images
    QString selectedImagePath;
};

#endif // EDITDIALOG_H

// All code above this comment was automatically generated by Qt Creator unless otherwise noted with a comment
