#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow> // Allows executing SQL queries in Qt. (SQLite)
#include <QSqlDatabase> // Needed because we use the EditDialog class in 'on_buttonEdit_clicked()'
#include "editdialog.h"

QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    void on_buttonAddPaint_clicked();

    void on_buttonDisplayPaints_clicked();

    void on_buttonClearAddedList_clicked();

    void on_buttonClearDisplayList_clicked();

    void on_buttonDelete_clicked();

    void on_buttonEdit_clicked();

    void on_buttonSearch_clicked();

    void on_buttonAddToShopping_clicked();

    void on_buttonDisplayShoppingList_clicked();

    void on_buttonRemoveFromShoppingList_clicked();

    void on_buttonUploadImage_clicked();

    void on_buttonImportCSV_clicked();

    void on_buttonExportCSV_clicked();

    void on_buttonHelp_clicked();

    void on_buttonSelectAll_clicked();

    void on_buttonDeselectAll_clicked();

    void on_buttonMainAddPaint_clicked();

    void on_buttonDoneAddPaint_clicked();

    void on_buttonMainManagePaints_clicked();

    void on_buttonDoneManagePaints_clicked();

    void on_buttonExportShoppingList_clicked();

private:
    Ui::MainWindow *ui;
    // Create SQLite database object named 'db'
    QSqlDatabase db;

    // Image path for uploaded images
    QString selectedImagePath;
    QString selectedImagePathMini;

    // Initialize the database (pass 'db' through the function)
    void initializeDatabase();
};
#endif // MAINWINDOW_H

// All code above this comment was automatically generated by Qt Creator unless otherwise noted with a comment
